[package]
name = "nanocore"
version = "0.1.0"
edition = "2024"
default-run = "nanocore"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
crossterm = "0.29.0"
hex = "0.4.3"
ratatui = "0.29.0"
